# Generated by Django 5.0.9 on 2024-11-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='footballer_curr_club',
            field=models.CharField(default='default clubname', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='footballer_name',
            field=models.CharField(default='default name', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='last_mod_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
